---

### write osp_install_run.json
- name: Get osp_install git info
  local_action: shell git describe --always
  register: git_describe

- name: Get undercloud timestamp
  local_action: shell date
  register: undercloud_date

- name:  Write osp_install_run.json
  template: src=osp_install_run.json dest=/etc/osp_install_run.json group=stack
### end write osp_install_run.json

- name: Make templates dir
  sudo_user: stack
  file: path=/home/stack/templates state=directory mode=0755

- name: Make nic-configs dir
  sudo_user: stack
  file: path=/home/stack/templates/nic-configs state=directory mode=0755

- name:  Write nic-config templates
  template: src={{ item.template_file }} dest=/home/stack/templates/nic-configs/{{ item.template_file }} owner=stack group=stack
  with_items:
    - { template_file: 'controller.yaml' }
    - { template_file: 'compute.yaml' }

- name:  Write environment files
  template: src={{ item.template_file }} dest=/home/stack/templates/{{ item.template_file }} owner=stack group=stack
  with_items:
    - { template_file: 'networking-cisco-environment.yaml' }
    - { template_file: 'nfs-environment.yaml' }

- name:  Write deploy_overcloud.sh
  template: src=deploy_overcloud.sh dest=/home/stack/bin/deploy_overcloud.sh owner=stack group=stack mode=755


###
# If still needed these commented out bits should be moved to (osp-prep-for-overcloud)
###

###
# Heat Review
###
- name: Check if heat review checked out
  stat: path=/home/stack/heat-review
  register: heat_review

- name:  Write heat-hack.patch
  template: src=heat-hack.patch dest=/home/stack/heat-hack.patch owner=stack group=stack

- name: Check for heat backup
  stat: path=/usr/share/openstack-tripleo-heat-templates.bak
  register: heat_backup

- name: Check on ironic-inspector firewall config
  sudo_user: stack
  shell: source /home/stack/stackrc && sudo iptables --list | grep ironic-inspector
  ignore_errors: true
  register: result

- debug: msg="Sysout output {{result.stdout}} and {{result.stdout.find("ironic-inspector")}}"

- name: Restart ironic-inspector
  sudo_user: stack
  shell: sudo service openstack-ironic-inspector restart && sleep 20
  when: result.stdout.find("ironic-inspector") == -1


###
# Deploy Overcloud
###

- name: Check for existing overcloud
  sudo_user: stack
  shell: source /home/stack/stackrc &&  heat stack-list | grep -q overcloud
  ignore_errors: true
  register: exiting_cloud_check

- name: Install overcloud
  sudo_user: stack
  shell: /home/stack/bin/deploy_overcloud.sh
  # up to 2 hours poll every minute
  async: 7200
  poll: 60
  when: deploy_overcloud and exiting_cloud_check|failed
