---

- name: Remove disk image files, if existing
  file: dest=/home/stack/images/{{ item.name }} state=absent
  with_items: "{{ disk_images }}"

- name: Make images dir
  sudo_user: stack
  file: path=/home/stack/images state=directory mode=0755

- name: Make /home/stack/bin
  sudo_user: stack
  file: path=/home/stack/bin state=directory mode=0755

- name: Write disk image scripts
  template: src={{ item.template_file }} dest=/home/stack/bin/{{ item.template_file }} owner=stack group=stack mode=0755
  with_items:
    - { template_file: 'build-disk-image.sh' }
    - { template_file: 'refresh-images.sh' }
    - { template_file: 'ipmi_address_to_uuid.py' }

- yum:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - rhosp-director-images
    - rhosp-director-images-ipa

- name: Unpack images
  sudo_user: stack
  shell: find /usr/share/rhosp-director-images/ -name '*.tar' -exec tar xf {} \;
  args:
    chdir: '/home/stack/images'

#- name: Download RHEL Guest Image
#  sudo_user: stack
#  get_url: url=http://memory.cisco.com/osp/RHEL_images/rhel-guest-image-7.2-20151102.0.x86_64.qcow2 dest=/home/stack/images/rhel-guest-image-7.2.qcow2
#  register: images_downloaded

- name: Install libguestfs-tools
  yum: name=libguestfs-tools

- name: Lets try and sleep a bit
  sudo_user: stack
  shell: sleep 30

- name: Patch overcloud-full.qcow2
  sudo_user: stack
  environment: proxy_env
  shell: "/home/stack/bin/build-disk-image.sh /home/stack/images/overcloud-full.qcow2"
  when: override_qcow

- name: Set root password in overcloud-full.qcow2
  sudo_user: stack
  shell: "virt-customize -a /home/stack/images/overcloud-full.qcow2 --root-password password:cisco123"
  when: not override_qcow and images_downloaded|success

- name: Allow password ssh in overcloud-full.qcow2
  sudo_user: stack
  shell: >
        virt-customize --selinux-relabel
        -a /home/stack/images/overcloud-full.qcow2
        --run-command "sed -i 's/.*PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config" &&
        virt-customize --selinux-relabel
        -a /home/stack/images/overcloud-full.qcow2
        --run-command "sed -i 's/PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
  when: not override_qcow and images_downloaded|success

- name: Download os-net-config patch (nic name natural sort fix)
  sudo_user: stack
  shell: cd /tmp/ && wget http://memory.cisco.com/osp7/patches/utils.py
  when: osp_version == 7

- name: Apply os-net-config patch (nic name natural sort fix)
  sudo_user: stack
  shell: virt-customize --selinux-relabel  -a /home/stack/images/overcloud-full.qcow2 --upload /tmp/utils.py:/usr/lib/python2.7/site-packages/os_net_config/utils.py
  when: osp_version == 7

#- name: Override overcloud-full.qcow2
#  sudo_user: stack
#  environment: proxy_env
#  get_url:
#    url: "{{ overcloud_full_override_url }}"
#    dest: "/home/stack/overcloud-full.qcow2"
#    sha256sum: "{{ overcloud_full_override_sha256sum }}"
#  when: override_qcow

- name: remove images from glance
  sudo_user: stack
  shell: source /home/stack/stackrc && glance image-delete bm-deploy-kernel bm-deploy-ramdisk overcloud-full overcloud-full-initrd overcloud-full-vmlinuz
  ignore_errors: true

- name: Upload disk images
  sudo_user: stack
  shell: cd /home/stack/images && source /home/stack/stackrc && openstack overcloud image upload

