---

- name: Create test-project
  sudo_user: stack
  shell: source /home/stack/overcloudrc && openstack project list | grep -q test-project || openstack project create --description 'Test Project' test-project

- name: Find test-project Id
  sudo_user: stack
  shell: source /home/stack/overcloudrc && openstack project list --format csv  --quote minimal | grep test-project | sed 's_,.*__'
  register: test_project_id

- name: Create test-user
  sudo_user: stack
  shell: source /home/stack/overcloudrc && openstack user list | grep -q test-user || openstack user create --project test-project --password password test-user

- name:  Write overcloudrc.test-project
  template: src=overcloudrc.test-project dest=/home/stack/overcloudrc.test-project owner=stack group=stack mode=755

- name: Add admin to test-project
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc && openstack role list --user admin --project test-project | grep -q admin ||
        openstack role add --user admin --project test-project admin

- name: Create test-net
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc &&
        neutron --os-tenant-name test-project --os-username test-user --os-password password net-list |
        grep -q test-net ||
        neutron --os-tenant-name test-project --os-username test-user --os-password password net-create test-net --tenant-id {{ test_project_id['stdout'] }}

- name: Create test-subnet
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc &&
        neutron --os-tenant-name test-project --os-username test-user --os-password password subnet-list |
        grep -q test-subnet ||
        neutron --os-tenant-name test-project --os-username test-user --os-password password subnet-create
        --name test-subnet
        --gateway 192.168.1.1
        test-net 192.168.1.0/24

- name: Create test-router (and ports)
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc &&
        neutron --os-tenant-name test-project --os-username test-user --os-password password router-list --format csv -c name |
        grep -q test-router ||
        (neutron --os-tenant-name test-project --os-username test-user --os-password password router-create test-router &&
        neutron --os-tenant-name test-project --os-username test-user --os-password password router-interface-add test-router test-subnet &&
        neutron --os-tenant-name test-project --os-username test-user --os-password password router-gateway-set test-router nova)

- name: Upload test-user pub key
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc &&
        nova --os-tenant-name test-project
        --os-username test-user
        --os-password password keypair-list |
        grep -q default_key ||
        nova --os-tenant-name test-project
        --os-username test-user
        --os-password password keypair-add
        --pub_key /home/stack/.ssh/id_rsa.pub default_key

- name: Download Cirros image
  sudo_user: stack
  get_url:
      url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
      dest: /home/stack/cirros-0.3.4-x86_64-disk.img
  register: cirros_image_downloaded

- name: Upload cirros disk image
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc &&
        glance image-list | grep -q "cirros 0.3.4" ||
        glance image-create --name='cirros 0.3.4'
        --is-public=true
        --container-format=bare
        --disk-format=qcow2 < /home/stack/cirros-0.3.4-x86_64-disk.img
  when: cirros_image_downloaded|success

- name: Set Security Group Rules
  sudo_user: stack
  shell: >
         source /home/stack/overcloudrc &&
         neutron --os-tenant-name test-project --os-username test-user --os-password password security-group-show default |
         grep icmp ||
         (neutron --os-tenant-name test-project --os-username test-user --os-password password security-group-rule-create --protocol icmp --direction ingress default &&
         neutron --os-tenant-name test-project --os-username test-user --os-password password security-group-rule-create --protocol icmp --direction egress default &&
         neutron --os-tenant-name test-project --os-username test-user --os-password password security-group-rule-create --protocol tcp --port-range-min 22 --port-range-max 22 --direction ingress default)

- name: Create Test VM
  sudo_user: stack
  shell: >
        source /home/stack/overcloudrc &&
        vm_net=$(neutron net-list --quote minimal --format csv -c id -c name | grep test-net | sed 's_,.*__') &&
        nova
        --os-tenant-name test-project
        --os-user-name test-user
        --os-password password
        boot cirros-test
        --flavor m1.tiny
        --image 'cirros 0.3.4'
        --security-groups default
        --nic net-id=$vm_net
        --key_name default_key