---

- name: install libffi-devel, git and other useful tools
  yum: name={{ item.name }}
  with_items:
    - { name: "python-junitxml" }


- name: Save node list
  sudo_user: stack
  shell: source /home/stack/stackrc && nova list > /home/stack/nova_list

- debug: msg="{{ local_report_dir }}"

- name: Upload node list to workspace node
  fetch:
    src: /home/stack/nova_list
    dest: "{{ local_report_dir }}"
    flat: yes


- name: Save director status
  sudo_user: stack
  shell: openstack-status > /home/stack/director_status

- name: Upload director status to workspace node
  fetch:
    src: /home/stack/director_status
    dest: "{{ local_report_dir }}"
    flat: yes


- name: Upload overcloudrc to workspace node
  fetch:
    src: /home/stack/overcloudrc
    dest: "{{ local_report_dir }}"
    flat: yes



#- name: Save Overcloud status
#  shell: openstack-status > /tmp/overcloud_status
#
#- name: Upload status to workspace node
#  fetch: src=/tmp/overcloud_status dest={{ workspace }}/target/
#        flat=yes


- name: Generate test report
  shell: testr last --subunit | subunit-1to2 | subunit2junitxml --output-to=tempest_results.xml
  args:
    chdir: /usr/share/openstack-tempest-kilo/
  ignore_errors: yes

- name: Upload test report
  fetch:
    src: /usr/share/openstack-tempest-kilo/tempest_results.xml
    dest: "{{ local_report_dir }}"
    flat: yes