---
- hosts: "{{ director_node_ssh_ip }}"
  connection: ssh
  roles:
      - ha-tenant-orphan-assassin
#    - add-test-gateway-ip
#    - osp-test-data

    - read-overcloudrc-props
    - rh-tempest
# TODO: need to resolve issues after merge (report_status and run_tests conflict)
#    - run_tests
    - report_status
