resource_registry:
  OS::TripleO::AllNodesExtraConfig: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/all_nodes/neutron-ml2-cisco-nexus-ucsm.yaml
{% if network_isolation %}
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
{% else %}
  OS::TripleO::Compute::Net::SoftwareConfig: /usr/share/openstack-tripleo-heat-templates/net-config-bridge.yaml
{% endif %}
{% if osp_version == 8 %}
  OS::TripleO::NodeExtraConfig: /home/stack/templates/disable-selinux.yaml
{% endif %}

parameter_defaults:

  InternalApiNetworkVlanID: {{ testbed_vlan }}
  StorageNetworkVlanID: {{ storage_vlan }}
  StorageMgmtNetworkVlanID: {{ storage_mgmt_vlan }}
  TenantNetworkVlanID: {{ tenant_network_vlan }}
  EC2MetadataIp: {{ undercloud_local_ip_simple }}
  ControlPlaneDefaultRoute: {{ undercloud_network_gateway }}

  ExternalNetCidr: {{ overcloud_external_ip_cidr }}
  ExternalAllocationPools: [{'start': '{{ overcloud_external_ip_start }}', 'end': '{{ overcloud_external_ip_end }}'}]
  ExternalNetworkVlanID: {{ overcloud_external_vlan }}
  ExternalInterfaceDefaultRoute: {{ overcloud_external_gateway }}

  DnsServers: ["{{ dns_server_1 }}"]
  NeutronExternalNetworkBridge: "{{ neutron_external_bridge }}"


  NetworkUCSMIp: '{{ network_ucsm_ip }}'
  NetworkUCSMUsername: '{{ network_ucsm_username }}'
  NetworkUCSMPassword: '{{ network_ucsm_password }}'
  NetworkUCSMHostList: '{{ network_ucsm_host_list }}'
{% if ucsm_support_pci_devs %}
  NetworkUCSMSupportedPciDevs: {{ ucsm_support_pci_devs }}
{% endif %}
  NetworkNexusConfig: {{ network_nexus_config|to_nice_json }}

  NetworkNexusManagedPhysicalNetwork: {{ network_nexus_managed_physical_network }}
  NetworkNexusVlanNamePrefix: '{{ network_nexus_vlan_name_prefix }}'
  NetworkNexusSviRoundRobin: '{{ network_nexus_svi_round_robin|to_json }}'
  NetworkNexusProviderVlanNamePrefix: '{{ network_nexus_provider_vlan_name_prefix }}'
  NetworkNexusPersistentSwitchConfig: '{{ network_nexus_persistent_switch_config|to_json }}'
  NetworkNexusSwitchHeartbeatTime: {{ network_nexus_switch_heartbeat_time }}
  NetworkNexusSwitchReplayCount: {{ network_nexus_switch_replay_count }}
  NetworkNexusProviderVlanAutoCreate: '{{ network_nexus_provider_vlan_auto_create|to_json }}'
  NetworkNexusProviderVlanAutoTrunk: '{{ network_nexus_provider_vlan_auto_trunk|to_json }}'
  NetworkNexusVxlanGlobalConfig: '{{ network_nexus_vxlan_global_config|to_json }}'
  NetworkNexusHostKeyChecks: '{{ network_nexus_host_key_checks|to_json }}'
  NeutronNetworkVLANRanges: '{{ network_nexus_vlan_range }}'

  NeutronMechanismDrivers: '{{ neutron_mechanism_drivers }}'

  NeutronTypeDrivers: '{{ type_driver }}'
  NeutronNetworkType: '{{ network_type }}'
  NetworkNexusVxlanVniRanges: '{{ vni_ranges }}'
  NetworkNexusVxlanMcastRanges: '{{ mcast_ranges }}'

{% if do_sriov %}
  NovaComputeExtraConfig:
    nova::compute::pci_passthrough_whitelist: [{"product_id":"0071", "address":"*:07:00.*", "vendor_id":"1137","physical_network": "{{ network_nexus_managed_physical_network }}" }]
{% endif %}

parameters:
  Debug: "{{ overcloud_debug }}"
#  controllerExtraConfig:
#    neutron::server::api_workers: 0
#    neutron::agents::metadata::metadata_workers: 0
#    neutron::server::rpc_workers: 0
